### PR TITLE
drop usage of callsite

### PR DESCRIPTION
**Pull request by krux02**
I try to get my PR [here](https://github.com/nim-lang/Nim/pull/11864) green. ``callsite`` will then only be available when explicity requested with ``--experimental:callsiteAccess``. This usage of callsite here though can be rewritten to not use it anymore, so no flag required.

### CODE REVIEW

**Comment by PMunch** [comment]
Why is it necessary to split the macros into a a normal and an `aux` variant?

**Comment by krux02** [comment]
The problem is, ``instantiationInfo`` does not work on macros yet. Therefore I made a template where instantiationInfo can be evaluated. I know it is ugly, sorry for that.

**Comment by PMunch** [comment]
Yeah I thought it was something like that. You say it doesn't work on macros _yet_, any idea when it will work on macros?

**Comment by krux02** [comment]
[My pr to main Nim](https://github.com/nim-lang/Nim/pull/11864) is blocked until this PR is merged. Will you merge it?

`callsite` will be implemented to work for macros as soon as it is implemented, I have it on my TODO but without a date. I think though this project should not wait for it nor use it yet, simply for compatibility.

**Pull request merged**
